// projects/packages/adapter-solid/src/index.ts
import type { WaeClient } from '@wae/client';
import { createComponent, createContext, type ParentProps, useContext } from 'solid-js';

const WaeContext = createContext<WaeClient>();

export type WaeProviderProps = ParentProps<{ client: WaeClient }>;

export function WaeProvider(props: WaeProviderProps) {
    return createComponent(WaeContext.Provider, {
        get value() {
            return props.client;
        },
        get children() {
            return props.children;
        },
    });
}

export function useWae(): WaeClient {
    const client = useContext(WaeContext);
    if (!client) {
        throw new Error('useWae() 需要包裹在 <WaeProvider client={…}> 内');
    }
    return client;
}

export default function solid(): { name: 'solid' } {
    return { name: 'solid' };
}

// projects/packages/adapter-react/src/index.ts
import type { WaeClient } from '@wae/client';
import { createContext, createElement, type ReactNode, useContext } from 'react';

const WaeContext = createContext<WaeClient | null>(null);

export type WaeProviderProps = {
    client: WaeClient;
    children?: ReactNode;
};

export function WaeProvider(props: WaeProviderProps) {
    return createElement(WaeContext.Provider, { value: props.client }, props.children);
}

export function useWae(): WaeClient {
    const client = useContext(WaeContext);
    if (!client) {
        throw new Error('useWae() 需要包裹在 <WaeProvider client={…}> 内');
    }
    return client;
}

/** 供 defineConfig({ frontend: { adapter: react() } }) 使用 */
export default function react(): { name: 'react' } {
    return { name: 'react' };
}
